name: Code style tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with dev --no-interaction --no-ansi

      - name: Ruff
        run: poetry run ruff check src/

      - name: Mypy
        run: poetry run mypy .
